package game;

import battleshipclient.Client;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cvsbilisim
 */
public class Game extends javax.swing.JFrame {

    public static Game ThisGame;
    public static Board enemyBoard;
    public static PlayerBoard playerBoard;
    public static JButton btnFire;
    public static boolean iAmReady = false;
    public static boolean rivalIsReady = false;
    public static JButton btnRestart;
    public static JFrame gameFrame;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        ThisGame = this;
        setResizable(false); // pencere yeniden boyutlandırılamaz
        setLocationRelativeTo(null); // ekranın ortasında açılır
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")



    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        btn_connect = new javax.swing.JButton();
        txt_rival_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(561, 379));
        jPanel1.setMinimumSize(new java.awt.Dimension(561, 379));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, 30));

        btn_connect.setBackground(new java.awt.Color(0, 204, 102));
        btn_connect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });
        jPanel1.add(btn_connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 156, 39));

        txt_rival_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_rival_name.setText("Rival");
        txt_rival_name.setEnabled(false);
        jPanel1.add(txt_rival_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 81, 39));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
       
        if (txt_name.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Lütfen bir isim giriniz.");

        } else {
            Client.Start("localhost", 2000);
            //başlangıç durumları

            btn_connect.setEnabled(false);
            txt_name.setEnabled(false);

            //btn_send_message.setEnabled(true);
            GameBoard boardScreen = new GameBoard();
                GameBoard.ThisGame = boardScreen;
                boardScreen.setSize(1216, 766);
                boardScreen.setVisible(true);
                boardScreen.showGameBoards();
                this.setVisible(false);
            this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                int result = JOptionPane.showConfirmDialog(
                        Game.this,
                        "Oyunu kapatmak istediğinize emin misiniz?",
                        "Çıkış Onayı",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (result == JOptionPane.YES_OPTION) {
                    Client.Stop();
                    dispose(); // pencereyi kapat
                    Message disconnect = new Message(Message.Message_Type.Disconnect);
                    Client.Send(disconnect);
                } else {
                    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); // kapatma iptal
                }
            }
        });

        }

    }//GEN-LAST:event_btn_connectActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_connect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_name;
    public javax.swing.JTextField txt_rival_name;
    // End of variables declaration//GEN-END:variables
}
