package game;



import battleshipclient.Client;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cvsbilisim
 */
public class Game extends javax.swing.JFrame {

    public static Game ThisGame;
    public static Board enemyBoard;
    public static PlayerBoard playerBoard;
    public static JButton btnFire;
    JFrame gameFrame = new JFrame("Battleship - Game Screen");
    

    /**
     * Creates new form Game
     */
    public Game() {
    initComponents();
    ThisGame = this; // Bu satır olmalı!
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void showGameBoards() {
        //JFrame gameFrame = new JFrame("Battleship - Game Screen");
        gameFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        gameFrame.setSize(1200, 700);
        gameFrame.setLayout(null); // Mutlak konumlandırma kullanıyoruz
        gameFrame.setBackground(Color.BLACK);

        // Enemy Board (küçük)
        enemyBoard = new game.Board();
        enemyBoard.drawBoard();
        enemyBoard.setBounds(50, 100, 300, 300);
        
        if(enemyBoard.getCount() == 17){
            String mesaj = "Kazandiniz" + txt_name.getText();
            JOptionPane.showMessageDialog(null, mesaj);
        }

        // Player Board (büyük)
        playerBoard = new game.PlayerBoard();
        playerBoard.drawBoard();
        playerBoard.setBounds(650, 100, 300, 300);

        // Etiketler
        JLabel lblEnemy = new JLabel(txt_rival_name.getText() + "'s board");
        lblEnemy.setBounds(50, 50, 200, 30);
        gameFrame.add(lblEnemy);

        JLabel lblPlayer = new JLabel(txt_name.getText() + "'s board");
        lblPlayer.setBounds(650, 50, 200, 30);
        gameFrame.add(lblPlayer);

        btnFire = new JButton("Fire");
        btnFire.setBounds(400, 90, 100, 30);
        btnFire.setEnabled(false); // Başlangıçta pasif

        JButton btnReady = new JButton("Ready");
        btnReady.setBounds(400, 50, 100, 30);
        btnReady.addActionListener(e -> {
            // Tüm gemiler yerleşti mi kontrolü
            if (playerBoard.getAllShipsPlaced()) {
                // Sunucuya ready mesajı gönder
                Message readyMsg = new Message(Message.Message_Type.Ready);
                Client.Send(readyMsg);
                System.out.println(txt_name.getText()+"'s ships");
                btnReady.setEnabled(false); // Butonu devre dışı bırak
                btnFire.setEnabled(true);
               
            } else {
                
            }
        });

        btnFire.addActionListener(e -> {
            int row = Game.enemyBoard.getRclick();
            int col = Game.enemyBoard.getCclick();

            if (row < 0 || col < 0) {
                txt_receive.setText("Lütfen bir hücre seçin!");
                return;
            }

            Message attackMsg = new Message(Message.Message_Type.Attack);
            attackMsg.content = row + "," + col;
            Client.Send(attackMsg);
            
            

            btnFire.setEnabled(false);  // Sırayı rakibe ver
            txt_receive.setText("Saldırı gönderildi: " + (char) (row + 'A') + (col + 1));
        });
        gameFrame.add(btnReady);
        gameFrame.add(btnFire);

        gameFrame.add(enemyBoard);
        gameFrame.add(playerBoard);

        gameFrame.setVisible(true);
        this.setVisible(false);
        
        gameFrame.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        Client.Stop();
    }
});

    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        btn_connect = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();
        txt_rival_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_send = new javax.swing.JTextArea();
        btn_send_message = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_receive = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        txt_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        btn_connect.setBackground(new java.awt.Color(0, 204, 102));
        btn_connect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });

        btn_start.setBackground(new java.awt.Color(0, 204, 204));
        btn_start.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        txt_rival_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_rival_name.setText("Rival");
        txt_rival_name.setEnabled(false);

        txt_send.setColumns(20);
        txt_send.setRows(5);
        jScrollPane1.setViewportView(txt_send);

        btn_send_message.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_send_message.setText("Send");
        btn_send_message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_send_messageActionPerformed(evt);
            }
        });

        txt_receive.setColumns(20);
        txt_receive.setRows(5);
        jScrollPane2.setViewportView(txt_receive);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_send_message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_rival_name, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rival_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_send_message)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        
        if(txt_name.getText().isEmpty()){
                
            JOptionPane.showMessageDialog(null, "Lütfen bir isim giriniz.");

        }else{
        Client.Start("127.0.0.1", 2000);
        //başlangıç durumları

        btn_connect.setEnabled(false);
        txt_name.setEnabled(false);

        btn_send_message.setEnabled(true);
        ThisGame.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        Client.Stop();
    
    }});
        
        }

    }//GEN-LAST:event_btn_connectActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        if (Client.socket != null && Client.socket.isConnected()) {
            if (txt_rival_name.getText().equals("Rival")) {
                // Henüz eşleşme yoksa
                txt_receive.setText("Rakip bekleniyor...");

                // Sunucuya pair durumunu sorgula (isteğe bağlı)
                Message msg = new Message(Message.Message_Type.PairStatus);
                msg.content = "Pair durumu sorgulama";
                Client.Send(msg);
            } else {
                // Eşleşme varsa
                txt_receive.setText("Eşleşme sağlandı! Oyun başlayabilir.");

                // Oyun başlatma mesajını gönder (isteğe bağlı)
                Message msg = new Message(Message.Message_Type.Start);
                Client.Send(msg);

            }
        } else {
            txt_receive.setText("Önce sunucuya bağlanmalısınız!");
        
        }
        this.showGameBoards();
        //btn_start.setEnabled(false);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_send_messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_send_messageActionPerformed
        //metin mesajı gönder
        Message msg = new Message(Message.Message_Type.Text);
        String x = txt_send.getText();
        msg.content = txt_send.getText();
        Client.Send(msg);
        txt_send.setText("");
    }//GEN-LAST:event_btn_send_messageActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_connect;
    public javax.swing.JButton btn_send_message;
    public javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField txt_name;
    public javax.swing.JTextArea txt_receive;
    public javax.swing.JTextField txt_rival_name;
    public javax.swing.JTextArea txt_send;
    // End of variables declaration//GEN-END:variables
}
